name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - numpy
  - xarray 
  - matplotlib
  - scipy
  - numba
  - sklearn
  - cartopy
  - shapely
  - dask
  - pip
  - pip:
      - sphinx-pythia-theme
